print("vamos a ver el promedio de 5 numeros")
print("Dame el numero 1:")
num1 = float(input())
print("Dame el numero 2:")
num2 = float(input())
print("Dame el numero 3:")
num3 = float(input())
print("Dame el numero 4:")
num4 = float(input())
print("Dame el numero 5:")
num5 = input()
promedio = (num1 + num2 + num3 + num4 + num5)/5
print("Dado los datos obtenidos el promedio es de:" + promedio)
